# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

asSparseMat <- function(inX) {
    .Call('_ungroup_asSparseMat', PACKAGE = 'ungroup', inX)
}

SparseProd <- function(inX, inY) {
    .Call('_ungroup_SparseProd', PACKAGE = 'ungroup', inX, inY)
}

pclmloop <- function(C, P, B, y, maxiter, tol) {
    .Call('_ungroup_pclmloop', PACKAGE = 'ungroup', C, P, B, y, maxiter, tol)
}

