# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

asSparseMat <- function(X) {
    .Call('_ungroup_asSparseMat', PACKAGE = 'ungroup', X)
}

pclm_loop <- function(C, P, B, y, maxiter, tol) {
    .Call('_ungroup_pclm_loop', PACKAGE = 'ungroup', C, P, B, y, maxiter, tol)
}

